// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleView } from "./RuleView";

/**
 * Vista serializable del ruleset para el frontend
 */
export type ChainView = { name: string, policy: string | null, rules: Array<RuleView>, };
