// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestResult } from "./TestResult";

export type CheckResult = { results: Array<TestResult>, all_passed: boolean, 
/**
 * Porcentaje de tests pasados (0.0 – 1.0).
 */
score: number, };
