// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedRule } from "./ParsedRule";
import type { RulesetView } from "./RulesetView";

export type ExecuteResult = { ok: boolean, ast: ParsedRule | null, error: string | null, humanize: string | null, ruleset: RulesetView, };
