// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostView } from "./HostView";
import type { RulesetView } from "./RulesetView";

export type LevelView = { index: number, id: string, titulo: string, cuento: string, mision: string, pistas: Array<string>, recompensa: string, hosts: Array<HostView>, ruleset: RulesetView, };
