// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortSpec } from "./PortSpec";

export type MatchKind = { "Protocol": string } | { "Source": string } | { "Destination": string } | { "InInterface": string } | { "OutInterface": string } | { "DPort": PortSpec } | { "SPort": PortSpec } | { "State": Array<string> } | { "CtState": Array<string> } | { "IcmpType": string } | { "Comment": string };
