// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchKind } from "./MatchKind";

export type Match = { negated: boolean, kind: MatchKind, };
