// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Proto } from "./Proto";

/**
 * Paquete de red que atraviesa el firewall simulado.
 * Las IPs se almacenan como strings para facilitar la serialización.
 */
export type Packet = { src_ip: string, dst_ip: string, src_port: number, dst_port: number, proto: Proto, in_iface: string, out_iface: string, 
/**
 * Máscara de bits ConnState (STATE_NEW, STATE_ESTABLISHED, …)
 */
state: number, };
