// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progreso del jugador.
 */
export type Progress = { 
/**
 * Índice 0-based del último nivel desbloqueado.
 * 0 = solo el primer nivel disponible.
 */
unlocked_until: number, 
/**
 * IDs de los niveles completados.
 */
completed: Array<string>, };
