// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Protocolo de red de un paquete.
 */
export type Proto = "All" | "Tcp" | "Udp" | "Icmp";
