// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chain } from "./Chain";
import type { Match } from "./Match";
import type { Target } from "./Target";

export type RuleCommand = { "Append": { chain: Chain, matches: Array<Match>, target: Target, } } | { "Insert": { chain: Chain, pos: number | null, matches: Array<Match>, target: Target, } } | { "Delete": { chain: Chain, rule_num: number | null, } } | { "Flush": { chain: Chain | null, } } | { "Policy": { chain: Chain, target: Target, } } | { "List": { chain: Chain | null, } } | { "NewChain": string } | { "DeleteChain": string | null };
