// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainView } from "./ChainView";

export type RulesetView = { filter_input: ChainView, filter_output: ChainView, filter_forward: ChainView, nat_prerouting: ChainView, nat_postrouting: ChainView, };
