// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Target = "Accept" | "Drop" | { "Reject": { with: string | null, } } | { "Log": { prefix: string | null, } } | "Masquerade" | { "Snat": { to: string, } } | { "Dnat": { to: string, } } | "Return" | { "Jump": string };
