// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Packet } from "./Packet";

/**
 * Un paso de la evaluación de un paquete a través del pipeline.
 */
export type TraceStep = { table: string, chain: string, 
/**
 * Índice de la regla (0-based); -1 = política por defecto.
 */
rule_idx: number, 
/**
 * Veredicto aplicado: "ACCEPT", "DROP", "REJECT", "RETURN", "JUMP", "CONTINUE"
 */
verdict: string, 
/**
 * Estado del paquete en este paso (puede variar tras DNAT/SNAT).
 */
pkt: Packet, };
