// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TraceStep } from "./TraceStep";

/**
 * Registro completo de la evaluación de un paquete a través del pipeline.
 */
export type Trace = { steps: Array<TraceStep>, };
